import images from "./images/index";

export const data = [
  {
    id: 1,
    title: "2.43: Seiin High School Boys Volleyball Team",
    year: "2021 Winter",
    image: images.image1,
    type: "Anime",
    link: "https://myanimelist.net/anime/40679/243__Seiin_Koukou_Danshi_Volley-bu",
  },
  {
    id: 2,
    title: "86: Eighty-Six",
    year: "2021 Spring",
    image: images.image2,
    type: "Anime",
    link: "https://myanimelist.net/anime/41457/86",
  },
  {
    id: 3,
    title: "86: Eighty-Six Part 2",
    year: "2021 Fall",
    image: images.image3,
    type: "Anime",
    link: "https://myanimelist.net/anime/48569/86_Part_2",
  },
  {
    id: 4,
    title: "Ajin: Demi-Human",
    year: "2016 Winter",
    image: images.image4,
    type: "Anime",
    link: "https://myanimelist.net/anime/31580/Ajin",
  },
  {
    id: 5,
    title: "Ajin: Demi-Human 2nd Season",
    year: "2016 Fall",
    image: images.image5,
    type: "Anime",
    link: "https://myanimelist.net/anime/33253/Ajin_Part_2",
  },
  {
    id: 6,
    title: "A Lull in the Sea",
    year: "2013 Fall",
    image: images.image6,
    type: "Anime",
    link: "https://myanimelist.net/anime/16067/Nagi_no_Asu_kara",
  },
  {
    id: 7,
    title: "Amagi Brilliant Park",
    year: "2014 Fall",
    image: images.image7,
    type: "Anime",
    link: "https://myanimelist.net/anime/22147/Amagi_Brilliant_Park",
  },
  {
    id: 8,
    title: "AMAIM Warrior at the Borderline",
    year: "2021 Fall",
    image: images.image8,
    type: "Anime",
    link: "https://myanimelist.net/anime/48466/Kyoukai_Senki",
  },
  {
    id: 9,
    title: "AMAIM Warrior at the Borderline: Part II",
    year: "2022 Spring",
    image: images.image9,
    type: "Anime",
    link: "https://myanimelist.net/anime/50678/Kyoukai_Senki_Part_2",
  },
  {
    id: 10,
    title: "Angel Beats!",
    year: "2010 Spring",
    image: images.image10,
    type: "Anime",
    link: "https://myanimelist.net/anime/6547/Angel_Beats",
  },
  {
    id: 11,
    title: "Ao Ashi",
    year: "2022 Spring",
    image: images.image11,
    type: "Anime",
    link: "https://myanimelist.net/anime/49052/Ao_Ashi",
  },
  {
    id: 12,
    title: "Arknights: Prelude to Dawn",
    year: "2022 Fall",
    image: images.image12,
    type: "Anime",
    link: "https://myanimelist.net/anime/50205/Arknights__Reimei_Zensou",
  },
  {
    id: 13,
    title: "A Silent Voice",
    year: "2016 Fall",
    image: images.image13,
    type: "Anime",
    link: "https://myanimelist.net/anime/28851/Koe_no_Katachi",
  },
  {
    id: 14,
    title: "Attack on Titan",
    year: "2013 Spring",
    image: images.image14,
    type: "Anime",
    link: "https://myanimelist.net/anime/16498/Shingeki_no_Kyojin",
  },
  {
    id: 15,
    title: "Attack on Titan 2nd Season",
    year: "2017 Spring",
    image: images.image15,
    type: "Anime",
    link: "https://myanimelist.net/anime/25777/Shingeki_no_Kyojin_Season_2",
  },
  {
    id: 16,
    title: "Attack on Titan 3rd Season",
    year: "2018 Summer",
    image: images.image16,
    type: "Anime",
    link: "https://myanimelist.net/anime/35760/Shingeki_no_Kyojin_Season_3",
  },
  {
    id: 17,
    title: "Attack on Titan 3rd Season Part II",
    year: "2019 Spring",
    image: images.image17,
    type: "Anime",
    link: "https://myanimelist.net/anime/38524/Shingeki_no_Kyojin_Season_3_Part_2",
  },
  {
    id: 18,
    title: "Attack on Titan The Final Season",
    year: "2021 Winter",
    image: images.image18,
    type: "Anime",
    link: "https://myanimelist.net/anime/40028/Shingeki_no_Kyojin__The_Final_Season",
  },
  {
    id: 19,
    title: "Attack on Titan The Final Season Part II",
    year: "2022 Winter",
    image: images.image19,
    type: "Anime",
    link: "https://myanimelist.net/anime/48583/Shingeki_no_Kyojin__The_Final_Season_Part_2",
  },
  {
    id: 20,
    title: "Azur Lane",
    year: "2019 Fall",
    image: images.image20,
    type: "Anime",
    link: "https://myanimelist.net/anime/38328/Azur_Lane",
  },
  {
    id: 21,
    title: "Beatless",
    year: "2018 Winter",
    image: images.image21,
    type: "Anime",
    link: "https://myanimelist.net/anime/36516/Beatless",
  },
  {
    id: 22,
    title: "Beatless: Final Stage",
    year: "2018 Summer",
    image: images.image22,
    type: "Anime",
    link: "https://myanimelist.net/anime/38020/Beatless_Final_Stage",
  },
  {
    id: 23,
    title: "Beyond the Boundary",
    year: "2013 Fall",
    image: images.image23,
    type: "Anime",
    link: "https://myanimelist.net/anime/18153/Kyoukai_no_Kanata",
  },
  {
    id: 24,
    title: "Black Bullet",
    year: "2014 Spring",
    image: images.image24,
    type: "Anime",
    link: "https://myanimelist.net/anime/20787/Black_Bullet",
  },
  {
    id: 25,
    title: "Blade Dance of the Elementalers",
    year: "2014 Summer",
    image: images.image25,
    type: "Anime",
    link: "https://myanimelist.net/anime/22877/Seireitsukai_no_Blade_Dance",
  },
  {
    id: 26,
    title: "Blood Blockade Battlefront",
    year: "2015 Spring",
    image: images.image26,
    type: "Anime",
    link: "https://myanimelist.net/anime/24439/Kekkai_Sensen",
  },
  {
    id: 27,
    title: "Blood Blockade Battlefront & Beyond",
    year: "2017 Fall",
    image: images.image27,
    type: "Anime",
    link: "https://myanimelist.net/anime/34451/Kekkai_Sensen___Beyond",
  },
  {
    id: 28,
    title: "Blue Exorcist",
    year: "2011 Spring",
    image: images.image28,
    type: "Anime",
    link: "https://myanimelist.net/anime/9919/Ao_no_Exorcist",
  },
  {
    id: 29,
    title: "Blue Exorcist: Kyoto Saga",
    year: "2017 Winter",
    image: images.image29,
    type: "Anime",
    link: "https://myanimelist.net/anime/33506/Ao_no_Exorcist__Kyoto_Fujouou-hen",
  },
  {
    id: 30,
    title: "Blue Lock",
    year: "2022 Fall",
    image: images.image30,
    type: "Anime",
    link: "https://myanimelist.net/anime/49596/Blue_Lock",
  },
  {
    id: 31,
    title: "Bottom-tier Character Tomozaki",
    year: "2021 Winter",
    image: images.image31,
    type: "Anime",
    link: "https://myanimelist.net/anime/40530/Jaku-Chara_Tomozaki-kun",
  },
  {
    id: 32,
    title: "Campione!",
    year: "2012 Summer",
    image: images.image32,
    type: "Anime",
    link: "https://myanimelist.net/anime/12293/Campione_Matsurowanu_Kamigami_to_Kamigoroshi_no_Maou",
  },
  {
    id: 33,
    title: "Cautious Hero: The Hero Is Overpowered but Overly Cautious",
    year: "2019 Fall",
    image: images.image33,
    type: "Anime",
    link: "https://myanimelist.net/anime/38659/Shinchou_Yuusha__Kono_Yuusha_ga_Ore_Tueee_Kuse_ni_Shinchou_Sugiru",
  },
  {
    id: 34,
    title: "Charlotte",
    year: "2015 Summer",
    image: images.image34,
    type: "Anime",
    link: "https://myanimelist.net/anime/28999/Charlotte",
  },
  {
    id: 35,
    title: "Chivalry of a Failed Knight",
    year: "2015 Fall",
    image: images.image35,
    type: "Anime",
    link: "https://myanimelist.net/anime/30296/Rakudai_Kishi_no_Cavalry",
  },
  {
    id: 36,
    title: "Classroom of the Elite",
    year: "2017 Summer",
    image: images.image36,
    type: "Anime",
    link: "https://myanimelist.net/anime/35507/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e",
  },
  {
    id: 37,
    title: "Classroom of the Elite 2nd Season",
    year: "2022 Summer",
    image: images.image37,
    type: "Anime",
    link: "https://myanimelist.net/anime/51096/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_2nd_Season",
  },
  {
    id: 38,
    title: "Combatants Will Be Dispatched!",
    year: "2021 Spring",
    image: images.image38,
    type: "Anime",
    link: "https://myanimelist.net/anime/41456/Sentouin_Hakenshimasu",
  },
  {
    id: 39,
    title: "DARLING in the FRANXX",
    year: "2018 Winter",
    image: images.image39,
    type: "Anime",
    link: "https://myanimelist.net/anime/35849/Darling_in_the_FranXX",
  },
  {
    id: 40,
    title: "Darwin's Game",
    year: "2020 Winter",
    image: images.image40,
    type: "Anime",
    link: "https://myanimelist.net/anime/38656/Darwins_Game",
  },
  {
    id: 41,
    title: "Date a Live",
    year: "2013 Spring",
    image: images.image41,
    type: "Anime",
    link: "https://myanimelist.net/anime/15583/Date_A_Live",
  },
  {
    id: 42,
    title: "Date a Live II",
    year: "2014 Spring",
    image: images.image42,
    type: "Anime",
    link: "https://myanimelist.net/anime/19163/Date_A_Live_II",
  },
  {
    id: 43,
    title: "Date a Live III",
    year: "2019 Winter",
    image: images.image43,
    type: "Anime",
    link: "https://myanimelist.net/anime/36633/Date_A_Live_III",
  },
  {
    id: 44,
    title: "Date a Live IV",
    year: "2022 Spring",
    image: images.image44,
    type: "Anime",
    link: "https://myanimelist.net/anime/41461/Date_A_Live_IV",
  },
  {
    id: 45,
    title: "Death March to the Parallel World Rhapsody",
    year: "2018 Winter",
    image: images.image45,
    type: "Anime",
    link: "https://myanimelist.net/anime/34497/Death_March_kara_Hajimaru_Isekai_Kyousoukyoku",
  },
  {
    id: 46,
    title: "Demon Slayer: Kimetsu no Yaiba",
    year: "2019 Spring",
    image: images.image46,
    type: "Anime",
    link: "https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba",
  },
  {
    id: 47,
    title: "Demon Slayer: Kimetsu no Yaiba - Swordsmith Village Arc",
    year: "2023 Spring",
    image: images.image47,
    type: "Anime",
    link: "https://myanimelist.net/anime/51019/Kimetsu_no_Yaiba__Katanakaji_no_Sato-hen",
  },
  {
    id: 48,
    title: "Dragon Ball Super",
    year: "2015 Summer",
    image: images.image48,
    type: "Anime",
    link: "https://myanimelist.net/anime/30694/Dragon_Ball_Super?cat=anime",
  },
  {
    id: 49,
    title: "Drifters",
    year: "2016 Fall",
    image: images.image49,
    type: "Anime",
    link: "https://myanimelist.net/anime/31339/Drifters",
  },
  {
    id: 50,
    title: "Engage Kiss",
    year: "2022 Summer",
    image: images.image50,
    type: "Anime",
    link: "https://myanimelist.net/anime/51417/Engage_Kiss",
  },
];
